version: '3'

services:
  web:
    build: ./web
    environment:
      - TODO_SERVICE_URL=http://localhost:8081
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - service
  service:
    build: ./service
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todo_dev
      - FLASK_RUN_PORT=8081
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    volumes:
      - ./service:/usr/src/app
    ports:
      - "8081:8081"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; flask run'
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=todo_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data:
