version: '3'

services:
  web:
    build: ./web
    environment:
      - SERVICE_URL=http://localhost:8081
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - service
  service:
    build: ./service
    volumes:
      - ./service:/usr/src/app
    ports:
      - "8081:8081"
